name: Build Android APK

on:
  push:
    branches:
      - Principal
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Java Development Kit
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet

      - name: Locate project and Build APK
        run: |
          # Encuentra automáticamente la carpeta donde se ubica main.py
          TARGET_DIR=$(dirname $(find . -maxdepth 3 -name "main.py" -print -quit))
          echo "Directorio encontrado: $TARGET_DIR"
          cd "$TARGET_DIR"
          flet build apk --no-interactive

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: "**/build/apk/*.apk"
